var MenuAlerts = [
    { label: "Accidente", value: "ACCIDENT", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Aceleración brusca", value: "BRUSH_ACCELERATION", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Activación de combustible", value: "FUEL_ACTIVATION", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Apagado de motor", value: "ENGINE_OFF", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Apertura de chapa", value: "LOCK_OPENING", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Apertura de puerta", value: "DOOR_OPENING", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Botón de pánico", value: "PANIC_BUTTON", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Cambio de operador", value: "CHANGE_DRIVER_TRAVEL", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Cierre de chapa", value: "LOCK_OFF", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Cierre de puerta", value: "DOOR_CLOSURE", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Cierre vial", value: "ROAD_CLOSURE", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Condiciones climaticas", value: "WEATHER_CONDITIONS", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Corte de combustible", value: "FUEL_CUT", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Desbloqueo de motor", value: "MOTOR_UNLOCKING", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Desenganche de caja", value: "DROP_TRAILER", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Desvío de ruta", value: "ROUTE_DETOUR", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Detección de Jammer", value: "JAMMER_DETECTED", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Detención no autorizada", value: "STAY_OUT_AT_A_INTEREST_POINT_WITHOUT_VELOCITY", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Encendido de motor", value: "ENGINE_IGNITION", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Entrada en punto de interés", value: "ENTRY_IN_A_POINT_OF_INTEREST", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Entrada en zona peligrosa", value: "GPS_GEOFENCE_EVENT_RISK", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Estadia en grupo de interés", value: "STAY_AT_A_INTEREST_GROUP", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Falla mecánica", value: "MECHANICAL_FAILURE", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Frenado brusco", value: "BRUSH_BRACKING", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Intento de Robo", value: "ATTEMPTED_ASSAULT", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Obra en vía", value: "WORK_ON_THE_ROAD", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "On Time Arrival", value: "OTA", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Otros", value: "OTHERS", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Pérdida de conexión", value: "LOST_GPS_CONNECTION", LT1: "SRC", LT2: "LT", LT3:"DTN" },
    { label: "Paro de motor", value: "ENGINE_STOP", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Peligro en vía", value: "DANGER_ON_THE_ROAD", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Rechazo de Entrega", value: "REJECTION_ON_TRAVEL", LT1: "SRC", LT2: "LT", LT3:"DTN" },
    { label: "Registro de evento logístico", value: "EVENT_REGISTER", LT1: "SRC", LT2: "LT", LT3:"DTN" },
    { label: "Retén", value: "RETAIN", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Riesgo de Entrega", value: "RISK_OF_LATE_ARRIVAL", LT1: "SRC", LT2: "LT", LT3:"DTN" },
    { label: "Salida de punto de interés", value: "OUTPUT_IN_A_POINT_OF_INTEREST", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Sin registro de evento vs cita", value: "NO_EVENT_REGISTRATION_WITH_APPOINTMENT", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Tamper", value: "TAMPER", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Temperatura fuera de rango", value: "OUT_OF_RANGE_TEMPERATURE", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Tráfico", value: "TRAFFIC", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Validación CCP", value: "VALIDATE_CCP", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Vehículo detenido", value: "STOPPED_VEHICLE", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Velocidad máxima", value: "MAXIMUN_SPEED", LT1: "SRC", LT2: "LT", LT3:"" },
    { label: "Viaje sin LT asignada", value: "TRANSLINE_NOT_ALLOCATED", LT1: "SRC", LT2: "", LT3:"" },
    { label: "Viaje sin placa tracto", value: "PLATE_NOT_ALLOCATED", LT1: "SRC", LT2: "LT", LT3:"" },
];

export default k = 12; // en el archivo test.js